let deviceData=[],gameData=[];
document.addEventListener('DOMContentLoaded',()=>{const user=requireUser(['LOCAL_ADMIN','GAME_ADMIN']);if(!user)return;renderSidebar('devices');if($('#device-form'))$('#device-form').addEventListener('submit',createDevice);if($('#sensor-form'))$('#sensor-form').addEventListener('submit',createSensor);if($('#actuator-form'))$('#actuator-form').addEventListener('submit',createActuator);if($('#sensors-list'))$('#sensors-list').addEventListener('click',deleteSensor);if($('#actuators-list'))$('#actuators-list').addEventListener('click',deleteActuator);loadAll();setInterval(loadAll,5000);});
async function loadAll(){try{const[d,g,s,a]=await Promise.all([apiGet('/devices'),apiGet('/games'),apiGet('/sensors'),apiGet('/actuators')]);deviceData=d;gameData=g;fillSelects();renderDevices(d);renderSensors(s);renderActuators(a);}catch(e){if($('#devices-list'))showMessage('#devices-list',e.message,'error-message');}}
function fillSelects(){const dev=deviceData.map(x=>`<option value="${x.id}">${escapeHtml(x.name)}</option>`).join('');const games=gameData.map(x=>`<option value="${x.id}">${escapeHtml(x.name)} - ${escapeHtml(x.type)}</option>`).join('');['#sensor-device','#actuator-device'].forEach(id=>{if($(id))$(id).innerHTML=dev;});['#sensor-game','#actuator-game'].forEach(id=>{if($(id))$(id).innerHTML=games;});}
function renderDevices(rows){if(!$('#devices-list'))return;$('#devices-list').innerHTML=rows.map(x=>`<article class="card"><div class="panel-title"><h3>${escapeHtml(x.name)}</h3><span class="badge status-${String(x.status).toLowerCase()}">${escapeHtml(x.status)}</span></div><p class="card-note">${escapeHtml(x.locale_name)} | ${x.sensors_count} sensori | ${x.actuators_count} attuatori</p><p class="meta">Ultimo contatto: ${formatDate(x.last_seen)}</p></article>`).join('')||'<div class="empty">Nessun dispositivo</div>';}
function renderSensors(rows){if(!$('#sensors-list'))return;$('#sensors-list').innerHTML=`<table><thead><tr><th>Nome</th><th>Gioco</th><th>Evento</th><th>Edge</th><th>Stato</th><th></th></tr></thead><tbody>${rows.map(x=>`<tr><td>${escapeHtml(x.name)}</td><td>${escapeHtml(x.game_name)}</td><td><span class="badge mqtt-badge">${escapeHtml(x.sensor_type)}</span></td><td>${escapeHtml(x.device_name)}</td><td>${escapeHtml(x.status)}</td><td><button class="btn danger" data-delete-sensor="${x.id}">Elimina</button></td></tr>`).join('')}</tbody></table>`;}
function renderActuators(rows){if(!$('#actuators-list'))return;$('#actuators-list').innerHTML=`<table><thead><tr><th>Nome</th><th>Gioco</th><th>Tipo</th><th>Stato simulato</th><th>Topic</th><th></th></tr></thead><tbody>${rows.map(x=>`<tr><td>${escapeHtml(x.name)}</td><td>${escapeHtml(x.game_name)}</td><td>${escapeHtml(x.actuator_type)}</td><td><span class="badge">${escapeHtml(x.state)}</span></td><td>${escapeHtml(x.mqtt_topic)}</td><td><button class="btn danger" data-delete-actuator="${x.id}">Elimina</button></td></tr>`).join('')}</tbody></table>`;}
async function createDevice(e){e.preventDefault();try{await apiPost('/devices',getFormData(e.target));e.target.reset();loadAll();}catch(err){alert(err.message);}}
async function createSensor(e){e.preventDefault();const body=getFormData(e.target);if(!body.mqtt_topic)delete body.mqtt_topic;try{await apiPost('/sensors',body);e.target.reset();loadAll();}catch(err){alert(err.message);}}
async function createActuator(e){e.preventDefault();try{await apiPost('/actuators',getFormData(e.target));e.target.reset();loadAll();}catch(err){alert(err.message);}}
async function deleteSensor(e){const b=e.target.closest('[data-delete-sensor]');if(!b)return;if(!confirm('Eliminare il sensore?'))return;try{await apiRequest(`/sensors/${b.dataset.deleteSensor}`,{method:'DELETE'});loadAll();}catch(err){alert(err.message);}}

async function deleteActuator(e){const b=e.target.closest('[data-delete-actuator]');if(!b)return;if(!confirm('Eliminare l attuatore?'))return;try{await apiRequest(`/actuators/${b.dataset.deleteActuator}`,{method:'DELETE'});loadAll();}catch(err){alert(err.message);}}
